# Generated by Django 5.2.7 on 2025-10-18 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_ingresso', models.DateField()),
                ('periodo', models.IntegerField()),
                ('cr_geral', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.curso')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('coordenador', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_da_semana', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.curso')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to='gestao_monitoria.alunoprofile')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.sala')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissaoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('total_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao_atividades', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to='gestao_monitoria.funcionarioprofile')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes_horas', to='gestao_monitoria.alunoprofile')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.alunoprofile')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.turma')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ap2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.alunoprofile')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.turma')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='gestao_monitoria.alunoprofile')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestao_monitoria.turma')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='gestao_monitoria.alunoprofile')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias_agendadas', to='gestao_monitoria.alunoprofile')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='gestao_monitoria.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_coordenadas', to='gestao_monitoria.funcionarioprofile')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.curso')),
                ('monitores', models.ManyToManyField(blank=True, related_name='vagas_inscritas', to='gestao_monitoria.alunoprofile')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.vaga'),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.alunoprofile')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_monitoria.vaga')),
            ],
        ),
    ]
