# Generated by Django 5.2.5 on 2025-09-25 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma_Casa.usuario')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_ingresso', models.DateField()),
                ('periodo', models.IntegerField()),
                ('cr_geral', models.FloatField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso')),
            ],
            bases=('plataforma_Casa.usuario',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma_Casa.usuario')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('coordenador', models.BooleanField(default=False)),
            ],
            bases=('plataforma_Casa.usuario',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.tipousuario'),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso')),
                ('monitores', models.ManyToManyField(blank=True, related_name='vagas_inscritas', to='plataforma_Casa.aluno')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_coordenadas', to='plataforma_Casa.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_da_semana', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.sala')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.vaga')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to='plataforma_Casa.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.turma')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ap2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.turma')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.vaga')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.aluno')),
            ],
        ),
    ]
