---
repo_url: https://github.com/Projetos-de-Extensao/PBE_25.2_8001_IV
site_author: Jonh Carvalho
site_name: PBE_25.2_8001_IV - Projeto de Extensão
copyright: Copyright ©️ 2025, Jonh Carvalho - IBMEC

nav: 
  - Home: index.md
  - Iniciação: 
      - Index: Iniciacao/index.md
      - Pesquisa: Iniciacao/pesquisa.md
      - 5w2h: Iniciacao/5w2h.md
      - Design Thinking: Iniciacao/design_thinking.md
      - Brainstorming: Iniciacao/Brainstorm.md
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Prototipagem Baixa Fidelidade: Iniciacao/prototipo_baixa_fidelidade.md
  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/das.md
      - Casos de Uso: Elaboracao/casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Diagrama de Sequência: Elaboracao/diagrama_de_sequencia.md
      - Protótipo de Alta Fidelidade: Elaboracao/prototipo_alta_fidelidade.md
  - Construção:
      - Index: Construcao/index.md
      - Git Issues: Construcao/git_issues.md
      - GitHub Projects: Construcao/github_projects.md
      - CodeSpace: Construcao/codespace.md
  - Transição:
      - Index: Transicao/index.md

extra:
  homepage: https://projetos-de-extensao.github.io/PBE_25.2_8001_IV
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Projetos-de-Extensao/PBE_25.2_8001_IV
      name: Repositório no GitHub
    - icon: fontawesome/solid/graduation-cap
      link: https://ibmec.br
      name: IBMEC
  consent:
    title: Consentimento de cookies
    description: >- 
      Usamos cookies para reconhecer suas visitas repetidas e preferências, bem como
      para medir a eficácia de nossa documentação e se os usuários
      encontram o que estão procurando. Com seu consentimento, você nos ajuda a
      melhorar nossa documentação.
    actions:
      - accept
      - reject
      - manage
  version:
    provider: mike

extra_css:
  - css/extra.css

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables

  - toc:
      permalink: true

plugins:
  - search:
      lang: 
        - pt
        - en
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      locale: pt_BR
  - git-committers:
      repository: Projetos-de-Extensao/PBE_25.2_8001_IV
      branch: main

theme:
  name: material
  language: pt-BR
  logo: assets/Ibmec_logo.png
  favicon: assets/Ibmec_logo.png
  palette:
    # Paleta para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    # Paleta para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Inter
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: material/school
