# Generated by Django 5.2.5 on 2025-09-24 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_coordenadas', to='plataforma_Casa.usuario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_da_semana', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.salas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.usuario')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.usuario')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.vaga')),
            ],
        ),
    ]
