# Generated by Django 5.2.5 on 2025-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_Casa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
