# Generated by Django 4.2.7 on 2025-10-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma_Casa", "0002_alter_usuario_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="avaliado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_realizadas",
                to="plataforma_Casa.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="comentario_avaliacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="data_avaliacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="data_comunicacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="nota_avaliacao",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="resultado_comunicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vaga",
            name="disciplina",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="numero_vagas",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vaga",
            name="responsabilidades",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Lista de Espera", "Lista de Espera"),
                    ("Rejeitado", "Rejeitado"),
                ],
                default="Pendente",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StatusPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_referencia", models.DateField()),
                ("total_horas", models.DecimalField(decimal_places=2, max_digits=6)),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Processando", "Processando"),
                            ("Pago", "Pago"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendente",
                        max_length=50,
                    ),
                ),
                ("data_processamento", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="plataforma_Casa.aluno",
                    ),
                ),
                (
                    "processado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagamentos_processados",
                        to="plataforma_Casa.funcionario",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="plataforma_Casa.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status de Pagamento",
                "verbose_name_plural": "Status de Pagamentos",
                "ordering": ["-mes_referencia"],
            },
        ),
        migrations.CreateModel(
            name="RegistroHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "total_horas",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                ("descricao_atividade", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Rejeitado", "Rejeitado"),
                        ],
                        default="Pendente",
                        max_length=50,
                    ),
                ),
                ("data_validacao", models.DateTimeField(blank=True, null=True)),
                ("observacao_validador", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horas_registradas",
                        to="plataforma_Casa.aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_horas",
                        to="plataforma_Casa.turma",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horas_validadas",
                        to="plataforma_Casa.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Horas",
                "verbose_name_plural": "Registros de Horas",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Histórico Escolar", "Histórico Escolar"),
                            ("Currículo", "Currículo"),
                            ("Carta de Motivação", "Carta de Motivação"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/%Y/%m/%d/")),
                ("nome_arquivo", models.CharField(max_length=255)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="plataforma_Casa.inscricao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvaliacaoMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_avaliacao", models.DateField()),
                (
                    "nota_desempenho",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                (
                    "nota_assiduidade",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("nota_didatica", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "nota_relacionamento",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("comentarios", models.TextField()),
                ("pontos_positivos", models.TextField(blank=True, null=True)),
                ("pontos_melhorar", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_feitas",
                        to="plataforma_Casa.funcionario",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to="plataforma_Casa.aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="plataforma_Casa.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Monitor",
                "verbose_name_plural": "Avaliações de Monitores",
                "ordering": ["-data_avaliacao"],
            },
        ),
    ]
