# Generated by Django 5.2.7 on 2025-10-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plataforma_Casa",
            "0003_adicionar_modelos_documento_registrohoras_statuspagamento",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Entrevista", "Entrevista"),
                    ("Aprovado", "Aprovado"),
                    ("Não Aprovado", "Não Aprovado"),
                ],
                default="Pendente",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
