# Generated by Django 4.2.7 on 2025-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma_Casa", "0003_inscricao_avaliado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuspagamento",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[
                    ("horario", "Por Hora"),
                    ("semestre", "Valor Fixo de Semestre"),
                ],
                default="semestre",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Entrevista", "Entrevista"),
                    ("Aprovado", "Aprovado"),
                    ("Não Aprovado", "Não Aprovado"),
                ],
                default="Pendente",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="statuspagamento",
            name="total_horas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Usado apenas para tipo 'Por Hora'",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="statuspagamento",
            name="valor_hora",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Usado apenas para tipo 'Por Hora'",
                max_digits=8,
            ),
        ),
    ]
