# Generated by Django 5.2 on 2025-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma_Casa", "0004_alter_inscricao_status_alter_usuario_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="funcao",
            field=models.CharField(
                blank=True, default="Professor", max_length=100, null=True
            ),
        ),
    ]
