# Generated by Django 4.2.7 on 2025-10-19 12:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma_Casa", "0004_statuspagamento_tipo_pagamento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statuspagamento",
            name="tipo_pagamento",
        ),
        migrations.RemoveField(
            model_name="statuspagamento",
            name="total_horas",
        ),
        migrations.RemoveField(
            model_name="statuspagamento",
            name="valor_hora",
        ),
        migrations.AlterField(
            model_name="statuspagamento",
            name="mes_referencia",
            field=models.DateField(
                help_text="Data final do semestre para este pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="statuspagamento",
            name="observacao",
            field=models.TextField(
                blank=True, help_text="Observações sobre o pagamento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="statuspagamento",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1500.00"),
                editable=False,
                max_digits=10,
            ),
        ),
    ]
