# Generated by Django 5.2 on 2025-10-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma_Casa", "0005_funcionario_funcao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialApoio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("lista", "Lista de Exercícios"),
                            ("tutorial", "Tutorial"),
                            ("outro", "Outro Material"),
                        ],
                        default="lista",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("arquivo", models.FileField(upload_to="materiais/%Y/%m/%d/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("publicado", models.BooleanField(default=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais_compartilhados",
                        to="plataforma_Casa.aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="plataforma_Casa.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material de Apoio",
                "verbose_name_plural": "Materiais de Apoio",
                "ordering": ["-criado_em"],
            },
        ),
    ]
