# Generated by Django 4.2.7 on 2025-10-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma_Casa", "0005_remove_statuspagamento_tipo_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacaomonitor",
            options={},
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="avaliador",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="comentarios",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="data_avaliacao",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="monitor",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="nota_assiduidade",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="nota_desempenho",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="nota_didatica",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="nota_relacionamento",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="pontos_melhorar",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="pontos_positivos",
        ),
        migrations.RemoveField(
            model_name="avaliacaomonitor",
            name="turma",
        ),
        migrations.RemoveField(
            model_name="inscricao",
            name="avaliado_por",
        ),
        migrations.RemoveField(
            model_name="inscricao",
            name="comentario_avaliacao",
        ),
        migrations.RemoveField(
            model_name="inscricao",
            name="data_avaliacao",
        ),
        migrations.RemoveField(
            model_name="inscricao",
            name="data_comunicacao",
        ),
        migrations.RemoveField(
            model_name="inscricao",
            name="nota_avaliacao",
        ),
        migrations.RemoveField(
            model_name="inscricao",
            name="resultado_comunicado",
        ),
    ]
