# Generated by Django 5.2.7 on 2025-10-31 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_Casa', '0008_migrar_dados_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['curso', 'periodo_sugerido', 'nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(help_text='Carga horária em horas'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(help_text='Código da disciplina (ex: CC101)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_criadas', to='plataforma_Casa.funcionario'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='plataforma_Casa.curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(help_text='Nome da disciplina', max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='periodo_sugerido',
            field=models.IntegerField(blank=True, help_text='Período sugerido para cursar', null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, related_name='e_pre_requisito_de', to='plataforma_Casa.disciplina'),
        ),
    ]
