# Generated by Django 5.2.7 on 2025-11-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_Casa', '0010_renomear_disciplina_nova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cr_geral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma_Casa.curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
