# Generated by Django 5.2.7 on 2025-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_Casa', '0011_alter_aluno_cr_geral_alter_aluno_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular com WhatsApp para contato', max_length=20, null=True),
        ),
    ]
