# Generated by Django 5.2.7 on 2025-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_Casa', '0012_aluno_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular para contato (com DDD)', max_length=20, null=True),
        ),
    ]
